apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-checkout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:JaviGG02/ab3-app.git
    targetRevision: dev
    path: manifests-ab3/retail-sample-app/checkout
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true