apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: catalog
spec:
  type: ExternalName
  # This will be dynamically replaced by the Aurora endpoint from the secret
  externalName: ${aws_rds_cluster.aurora.endpoint}
  ports:
  - port: 3306
