apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: public.ecr.aws/aws-containers/retail-store-sample-catalog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
          value: "mysql"
        - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
        - name: RETAIL_CATALOG_PERSISTENCE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: RETAIL_CATALOG_PERSISTENCE_DB_NAME
        - name: RETAIL_CATALOG_PERSISTENCE_USER
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: RETAIL_CATALOG_PERSISTENCE_USER
        - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: RETAIL_CATALOG_PERSISTENCE_PASSWORD
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 128m
            memory: 512Mi