apiVersion: v1
kind: Secret
metadata:
  name: orders-rabbitmq
data:
  RETAIL_ORDERS_MESSAGING_USERNAME: "Z3Vlc3Q="  # guest in base64
  RETAIL_ORDERS_MESSAGING_PASSWORD: "Z3Vlc3Q="  # guest in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "b3JkZXJz"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "M3o2c0dMaEd1bmZuMHhaYw=="