apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-ops-view
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - redis-deployment.yaml
  - ingress.yaml

patches:
  - path: amd64-patch.yaml
    target:
      kind: Deployment
      name: kube-ops-view
  - path: redis-amd64-patch.yaml
    target:
      kind: Deployment
      name: kube-ops-view-redis

commonLabels:
  app.kubernetes.io/name: kube-ops-view
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize