apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: ui
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  UI_THEME: "default"
  # Configure these endpoints to point to your other microservices
  CATALOG_ENDPOINT: "http://catalog.catalog.svc.cluster.local"
  CARTS_ENDPOINT: "http://carts.carts.svc.cluster.local"
  ORDERS_ENDPOINT: "http://orders.orders.svc.cluster.local"
  CHECKOUT_ENDPOINT: "http://checkout.checkout.svc.cluster.local"