apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd64
spec:
  template:
    metadata:
      labels:
        type: karpenter
        provisioner: amd64
        NodeGroupType: amd64
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand", "spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
      nodeClassRef:
        name: basic
        group: eks.amazonaws.com
        kind: NodeClass
  limits:
    cpu: 1000