apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-ops-view
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:JaviGG02/ab3-app.git
    targetRevision: dev
    path: manifests-ab3/kube-ops-view
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-ops-view
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true