# IN ORDER TO MAKE IT WORK, IT MUST DEPLOY A CLASSIC LB NOT AN ALB NOR ELB
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
  # - retail-app.yaml
  # - kube-ops-view-app.yaml
  - retail-ui-app.yaml
  - retail-carts-app.yaml
  # - retail-catalog-app.yaml
  # - retail-checkout-app.yaml
  - retail-orders-app.yaml
  # - retail-common-app.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd
    target:
      kind: ClusterRoleBinding
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: argocd-server