apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: not-important
spec:
  minReplicas: 6
  maxReplicas: 200
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # behavior:
  #   scaleUp:
  #     stabilizationWindowSeconds: 60
  #     policies:
  #     - type: Percent
  #       value: 100
  #       periodSeconds: 60
  #     - type: Pods
  #       value: 10
  #       periodSeconds: 60
  #     selectPolicy: Max
    # scaleDown:
    #   stabilizationWindowSeconds: 300
    #   policies:
    #   - type: Percent
    #     value: 10
    #     periodSeconds: 60