apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- carts.yaml
- catalog.yaml
- checkout.yaml
- orders.yaml
- ./ui/

patches:
- path: graviton-patch.yaml
  target:
    kind: Deployment