apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- catalog.yaml
- checkout.yaml
- ./orders/
- ./ui/
- ./carts/
- ./orders/
- pdb-patch.yaml


patches:
- path: graviton-patch.yaml
  target:
    kind: Deployment