apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./ui/
- ./catalog/
- ./checkout/
- ./orders/
- ./carts/
- pdb-patch.yaml


patches:
- path: graviton-patch.yaml
  target:
    kind: Deployment